export const front = {
  text: "前端",
  collapsed: true,
  items: [
    { text: "总览", link: "/src/front-end-rule/start" },
    { text: "vue3", link: "/src/front-end-rule/vue3" },
    { text: "vue-router", link: "/src/front-end-rule/vue-router" },
    { text: "pinia", link: "/src/front-end-rule/pinia" },
    { text: "nuxt", link: "/src/front-end-rule/nuxt" },
    { text: "uniapp", link: "/src/front-end-rule/uniapp" },
    { text: "react", link: "/src/front-end-rule/react" },
    { text: "taro", link: "/src/front-end-rule/taro" },
    { text: "electron", link: "/src/front-end-rule/electron" },
    { text: "chrome-extensions", link: "/src/front-end-rule/chrome-extensions.md" },
    { text: "wujie", link: "/src/front-end-rule/wujie.md" },
    { text: "typescript", link: "/src/front-end-rule/typescript.md" },
    { text: "vite", link: "/src/front-end-rule/vite.md" },
    { text: "puppeteer", link: "/src/front-end-rule/puppeteer.md" },
  ],
};
