export const nestjs = {
  text: "nestjs",
  collapsed: true,
  link: "/src/maintain/nestjs/1-start",
  items: [
    { text: "Quick Start", link: "/src/maintain/nestjs/1-start" },
    { text: "CLI", link: "/src/maintain/nestjs/2-cli" },
    { text: "Project Structure", link: "/src/maintain/nestjs/3-projectStructure" },
    { text: "Fundamental", link: "/src/maintain/nestjs/4-fundamental" },
    { text: "Decorator", link: "/src/maintain/nestjs/5-decorator" },
    { text: "Pipe", link: "/src/maintain/nestjs/6-pipe" },
    { text: "Middleware", link: "/src/maintain/nestjs/7-middleware" },
    { text: "Exception", link: "/src/maintain/nestjs/8-exception" },
    { text: "Guards", link: "/src/maintain/nestjs/9-guards" },
    { text: "Interceptors", link: "/src/maintain/nestjs/interceptors" },
    { text: "DTO", link: "/src/maintain/nestjs/dto" },
    { text: "Mongodb", link: "/src/maintain/nestjs/mongodb" },
    { text: "IOC & DI", link: "/src/maintain/nestjs/di" },
    { text: "File", link: "/src/maintain/nestjs/file" },
    { text: "Other", link: "/src/maintain/nestjs/other" },
  ],
};
